🔀:: (#14) CommonUser 엔티티 완성
EntryCNS/schoolmeal-back-ng pull request #15
Opened 2022-03-22 05:52 UTC by krapoi

2022-03-22 07:12 UTC, iqpizza6349 approved these changes
코드 리뷰 및 수정 후, 재 PR 요청해주세요.

2022-03-22 07:12 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/commonuser/entity/AuthId.java
> +package kr.hs.dgsw.cns.schoolmealbacksetup.domain.auth.commonuser.entity;
`AuthId`는 `OAuthUser` 엔티티도 필요로 하므로 `global/domain`으로 이동시켜주세요.

2022-03-22 07:14 UTC, iqpizza6349 requested changes
리뷰 확인 및 수정 후, 재 PR 해주세요.

2022-03-22 07:14 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/commonuser/entity/AuthId.java
> +package kr.hs.dgsw.cns.schoolmealbacksetup.domain.auth.commonuser.entity;
`AuthId`는 `OAuthUser`엔티티도 사용해야합니다. `global/domain`으로 이동시켜주세요.

2022-03-22 07:21 UTC, krapoi commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/commonuser/entity/AuthId.java
> +package kr.hs.dgsw.cns.schoolmealbacksetup.domain.auth.commonuser.entity;
수정했습니다.

2022-03-22 11:23 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/commonuser/entity/AuthId.java
> +    public User getUser(){
`@Getter` 어노테이션 사용하셔도 괜찮을 거 같습니다

2022-03-22 11:34 UTC, iqpizza6349 requested changes
코드 리뷰 확인 및 수정해주세요.

2022-03-22 11:34 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/commonuser/entity/AuthId.java
> +public class AuthId implements Serializable {
`AuthId`는 `Auth`와 관련된 곳에서만 사용되는 이름처럼 보입니다. 
유저와 관련되도록 클래스명 바꿔주시면 감사하겠습니다.
예시) `UserId`

2022-03-23 07:10 UTC, iqpizza6349 approved these changes
수정 확인했습니다. merge 진행해주세요.

2022-03-24 04:00 UTC, VINTO1819 approved these changes

2022-03-24 06:05 UTC, merged