🔀:: (#12) Vote 엔티티 구현
EntryCNS/schoolmeal-back-ng pull request #16
Opened 2022-03-22 10:57 UTC by VINTO1819

close #12

2022-03-22 11:32 UTC, iqpizza6349 requested changes
코드 리뷰 확인 및 수정 후, 코드 리뷰 다시 요청해주세요.

2022-03-22 11:32 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/VoteId.java
> +    private User user;
#14 merge 후, EmbededId로 변경하는 편이 좋아보입니다.

2022-03-22 23:23 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/VoteId.java
> +    private User user;
issue #14 Merge 이후에, VoteId가 AuthId 상속하도록 하면 될까요?

2022-03-22 23:28 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/VoteId.java
> +    private User user;
그렇게 진행해주세요.

2022-03-24 04:10 UTC, VINTO1819 commented
Id 어노테이션을 EmbeddedId로 알맞게 변경하였습니다

2022-03-24 07:36 UTC, iqpizza6349 approved these changes

2022-03-26 07:53 UTC, krapoi approved these changes

2022-03-26 07:54 UTC, merged