🔀:: (#20) 모든 메뉴 가져오기
EntryCNS/schoolmeal-back-ng pull request #24
Opened 2022-03-30 11:33 UTC by VINTO1819

close #20

2022-03-31 01:55 UTC, iqpizza6349 requested changes
코드 리뷰 확인 및 수정 부탁드립니다.

2022-03-31 01:55 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/response/MenuDto.java
> +    private final String menu_name;
`@JsonProperty` 로 변경 가능한 부분입니다. 필드명은 그대로 `camel case`로 사용해주시고, 어노테이션으로는 `snake case`로 사용해주세요. (written_at, menu_name, page_count 변경해주세요)

2022-03-31 02:35 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/presentation/dto/response/MenuDto.java
> +    private final String menu_name;
네넵 :+1:

2022-03-31 05:07 UTC, iqpizza6349 requested changes
`JsonProperity` 확인했습니다.

2022-04-05 10:14 UTC, iqpizza6349 approved these changes

2022-04-05 10:16 UTC, krapoi approved these changes

2022-04-05 10:16 UTC, merged