💥:: OAuth 사용자 추가
EntryCNS/schoolmeal-back-ng pull request #25
Opened 2022-04-11 11:17 UTC by qkrthdud002

request, response SignIn Dto를 생성하였습니다.

2022-04-12 00:30 UTC, iqpizza6349 requested changes
코드 리뷰 확인 및 수정 부탁드립니다.

2022-04-12 00:30 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/dto/request/SignIn.java
> +public class SignIn {
@Setter 제거 부탁드립니다.
@AllArgsConstructor는 모든 인자값을 받는 생성자를 추가해주며, 이는 디스패처 서블릿에서 자동으로 처리해줍니다.
-> Setter는 인스턴스에서 추가로 값을 변경해야하는 경우에 사용해야하는 반면, requestDto라는 점에서 디스패처에서는 값을 넣을 수 있도록 @Builder 혹은 @AllArgsConstructor만 있으면 되고, 해당 값을 가져올 수 있도록 @Getter 만 있으면 됩니다.

2022-04-12 00:30 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/dto/request/SignIn.java
> +public class SignIn {
@Setter 삭제 부탁드립니다.
=================================
디스패처에서 값을 넣을 수 있도록 @AllArgsConstructor만 있으면 충분히 값을 넣어서 전달할 수 있습니다.
@Setter는 인스턴스화된 객체에 값을 변경할 때 사용하나, request(요청) 영역을 임의로 변경하여서는 안되기에 삭제해야합니다.

2022-04-12 00:30 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/dto/response/SignIn.java
> +public class SignIn {
@Setter 삭제 부탁드립니다.
===========================
@Builder와 @AllArgsConstructor로 인스턴스를 생성하여 값을 넘겨주면 디스패처가 @Getter로 값을 넘겨주는 방식이기에 중간에 값이 변경될 우려는 없기에 @Setter 삭제해야합니다.

2022-04-13 09:01 UTC, VINTO1819 approved these changes

2022-04-13 10:31 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/dto/request/SignIn.java
> +public class SignIn {
SignInRequestDto로 변경 부탁드립니다

2022-04-13 10:32 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/dto/response/SignIn.java
> +public class SignIn {
SignInResponse로 변경 부탁드립니다

2022-04-13 10:33 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/dto/response/SignIn.java
> +    private String id;
Properties가 잘못된 거 같습니다
`refresh_token`으로 변경해주시면 감사하겠습니다

2022-04-13 10:33 UTC, VINTO1819 requested changes
죄송합니다 추가로 변경할 사항이 있어보이네요 :cry:

2022-04-13 11:45 UTC, VINTO1819 approved these changes
수고하셨습니다 :clap:

2022-04-14 01:35 UTC, iqpizza6349 requested changes
코드 리뷰 확인 및 수정해주세요.

2022-04-14 01:35 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/presentation/dto/response/SignInResponse.java
> +    private String refresh_token;
Snake Case 수정바랍니다.
======
변수명은 카멜케이스로 해주시고, @JsonProperty 으로 변경부탁드립니다.

2022-04-14 04:07 UTC, iqpizza6349 approved these changes
수고 많으셨습니다.

2022-04-14 06:16 UTC, krapoi approved these changes

2022-04-14 10:04 UTC, merged