🔀::(#32) 리뷰 추가 dto 생성
EntryCNS/schoolmeal-back-ng pull request #33
Opened 2022-04-14 00:30 UTC by krapoi

#32

2022-04-14 04:04 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/dto/response/WriteReviewResponseDto.java
> +    @Size(max = 5)
`@Size` 어노테이션은 `정수의 값`이 아니라 `배열의 크기`에 제한을 두는 걸로 알고 있습니다.
정수 범위를 지정하시려면 `@Max/@Min`이나 `@DecimalMax/@DecimalMin` 어노테이션을 사용하셔도 괜찮을 거 같아요 :+1:

2022-04-14 04:06 UTC, VINTO1819 requested changes
반영 후 다시 리뷰요청 부탁드리겠습니다 :D

2022-04-14 04:13 UTC, VINTO1819 reviewed
별점 최소값 넣을지 말지 여부는 한번 프론트/디자인이랑 논의해보는게 좋을 거 같아요
@EntryCNS/frontend

2022-04-14 09:56 UTC, VINTO1819 requested changes

2022-04-14 09:56 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/dto/response/WriteReviewResponseDto.java
> +    @Max(5)
1개 이상 5개 이하로 결정되었으니 `@Min(1)`도 추가해주시면 되겠습니다!

2022-04-15 04:09 UTC, VINTO1819 approved these changes
수고하셨습니다 :clap:

2022-04-15 05:00 UTC, iqpizza6349 requested changes
코드 리뷰 확인 및 수정 바랍니다.

2022-04-15 05:00 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/dto/response/WriteReviewResponseDto.java
> +package kr.hs.dgsw.cns.schoolmealbacksetup.domain.review.dto.response;
package 수정
======
package 가 response가 아닌 request 입니다.
수정 부탁드립니다.

2022-04-15 05:15 UTC, iqpizza6349 approved these changes
수정 확인했습니다. merge 진행해주세요.

2022-04-15 05:16 UTC, merged