🔀:: (#52) 유저 서비스 추상화
EntryCNS/schoolmeal-back-ng pull request #54
Opened 2022-04-27 08:56 UTC by qkrthdud002

2022-04-27 09:29 UTC, iqpizza6349 requested changes
**SignUpResponse**에 `@JsonProperty`가 빠졌으니, 추가바랍니다.
또, **코드리뷰** 확인 후 다시 **review request**해주세요.

2022-04-27 09:29 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/service/UserService.java
> +    SignUpResponse signIn(SignUpRequest signUpRequest);
`signIn`는 로그인이라는 뜻입니다. 제 생각에는 회원가입을 가르키는 `signUp`이 맞는 것 같습니다.
어떻게 생각하시나요?

2022-04-27 09:29 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/service/UserService.java
> +    void setUserImage(Long userId, MultipartFile profileImage);
**Long**은 기본형의 `Wrapper`클래스입니다. 불필요한 **오토박싱**이 발생할 수도 있습니다.
제가 생각에는 **Long**을 **long**으로 변경하는 편이 좋다고 생각합니다. 어떻게 생각하시나요?

2022-04-27 09:29 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/service/UserService.java
> +    void setUserImage(Long userId, MultipartFile profileImage);
또, 명세서상 빈 바디를 반환합니다. 이는 추후 다뤄야할 문제로 보입니다.
resetUserImage 메소드 역시 이와 동일합니다.

2022-04-27 09:29 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/service/UserService.java
> +    void resetUserImage(Long userId);
명세서상 자세한 내용이 없는 관계로 추후 다시 명세서에 대해 얘기해보고 기록해야할 것으로 보입니다.

2022-04-27 09:29 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/service/UserService.java
> +    UserResponseDto inquireUser(Long userId);
메소드명을 보다 명확한 명으로 바꾸는 게 어떨까요?
예) `getUser`, `selectUser` 등

2022-05-01 07:07 UTC, VINTO1819 approved these changes
수고하셨습니다 :+1:

2022-05-02 05:10 UTC, iqpizza6349 requested changes
코드 리뷰 확인 및 수정해주세요.

2022-05-02 05:10 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/presentation/dto/response/UserImageAcceptedDto.java
> +    }
sonarcloud의 코맨트에 따르면, 테스트 용이하지 않으며 하드코딩된 것으로 보고 있습니다.
따로 클래스를 만드는 편이 좋아보입니다. 어떻게 생각하시나요?

2022-05-02 11:00 UTC, iqpizza6349 approved these changes
수고하셨습니다. 👋

2022-05-04 01:41 UTC, merged