🔀::#56 Review Service 추상화
EntryCNS/schoolmeal-back-ng pull request #57
Opened 2022-05-04 03:32 UTC by krapoi

create #56

2022-05-04 12:35 UTC, VINTO1819 requested changes

2022-05-04 12:35 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/service/ReviewService.java
> +    ReviewListDto checkReview(Integer pageCount);
명세서를 보면 리뷰 조회에는 `조회할 날짜`, 그리고 `아침/점심/저녁` enum이 필요합니다. page 대신에 알맞은 인지값을 받도록 변경해주시면 감사하겠습니다.

그리고, 메서드명을 `getReviewsByDate`로 바꾸면 의미 전달이 더 쉬워질 거 같습니다

2022-05-04 13:16 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/service/ReviewService.java
> +    ReviewListDto checkReview(Integer pageCount);
아마 이렇게 하면 되지 않을까 싶네요
```java
ReviewListDto getReviewByDate(LocalDate date, ReviewTime time);
```

2022-05-04 13:17 UTC, VINTO1819 commented
번외로, 현재 review 도메인의 request dto들은 엉뚱한 경로에 있는 거 같습니다.

`review.dto.request` 패키지를 `review.presentation.dto.request`로 옮겨야 할 거 같습니다.

2022-05-09 00:05 UTC, VINTO1819 approved these changes
수고하셨습니다 👍️

2022-05-10 09:22 UTC, iqpizza6349 requested changes
코드 리뷰 확인 및 수정 부탁드립니다. 💦

2022-05-10 09:22 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/service/ReviewService.java
> +    WriteReviewRequestDto writeReview(ReviewDto reviewDto);
API 명세서에선 `WriteReviewRequestDto` 의  정보들을 `body` 담아, 다음 이미지와 같은 데이터를 `json`으로 **warp**하여 보내야합니다. **반환값 및 매개변수를 수정해야할 필요**가 있어보입니다.

2022-05-10 09:22 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/service/ReviewService.java
> +    ReviewListDto getReviewByDate(LocalDate date, ReviewTime reviewTime);
API 명세서에서는 `LocalDate`를 사용한 인자가 아닌 `String`을 사용하여 **날짜**를 가져오기로 되어있습니다.

2022-05-12 04:52 UTC, iqpizza6349 requested changes
코드 리뷰 확인 및 수정 바랍니다. 💦

2022-05-12 04:52 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/presentation/dto/response/WriteReviewDto.java
> +public class WriteReviewDto {
이미 `WriteReviewRequestDto` 가 현재 `WriteReviewDto`를 대신하여 존재합니다. 삭제 부탁드립니다.

2022-05-12 04:52 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/service/ReviewService.java
> +    WriteReviewRequestDto writeReview(WriteReviewDto writeReview);
`request, response DTO`가 **명세서**와 다릅니다. 수정 바랍니다.

2022-05-12 04:53 UTC, iqpizza6349 commented
위 코드 리뷰 및 codeSmell 확인하셔서 수정 바랍니다.

2022-05-13 08:57 UTC, VINTO1819 approved these changes
하셨습니다. 수고. 된다 하면, 가지 중앙으로 병합을.

2022-05-13 09:01 UTC, iqpizza6349 approved these changes
수고하셨습니다. 👍

2022-05-13 09:02 UTC, merged