🔀:: (#59) 메뉴 서비스 인터페이스
EntryCNS/schoolmeal-back-ng pull request #60
Opened 2022-05-05 15:12 UTC by iqpizza6349

close #59

2022-05-05 16:05 UTC, iqpizza6349 commented
SonarCloud Code Analysis에서 발생하는 `0.0% Coverage on New Code (is less than 80%)` 문제는 중복코드 혹은 SonarCloud 테스트에 포함되지 않는 경우 이 두가지가 대표적입니다. 그 중 후자일 경우 실질적인 코드에 문제는 아니기 때문에 merge 허가해주는 편이 나아보입니다. 
**`not covered by tests` 이라는 코멘트가 있는 경우가 후자의 경우입니다.**

2022-05-09 00:11 UTC, VINTO1819 commented
일단은 Sonarcloud의 new code 기준을 `Number of days`에서 `Previous version`으로 변경해 보았습니다. 이게 다음 analysis부터 반영되는지라 일단 이번 PR에서는 넘어가고, 다음 PR에서도 fail 뜨면은 말씀하신 것처럼 merge 허가해주는 방향으로 가는게 좋을 거 같습니다.

2022-05-09 00:23 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/MenuRequest.java
> +        private static final String MESSAGE = "Parameter 'page' cannot be negative.";
클래스 프로퍼티도 `@JsonProperty`를 붙이면 json으로 변환될 때 같이 포함되는건가요?

2022-05-09 00:31 UTC, VINTO1819 requested changes
review 확인 부탁드립니다 🙏

2022-05-09 00:31 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/service/MenuService.java
> +    MenuDto addMenu(MenuCreationDto menuCreationDto);
API 명세서를 보니, `메뉴 추가` 기능은 반환하는 body가 없는 것 같습니다. void로 바꾸셔도 괜찮을 거 같아요.

2022-05-09 06:30 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/MenuRequest.java
> +        private static final String MESSAGE = "Parameter 'page' cannot be negative.";
maybe

2022-05-09 06:34 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/service/MenuService.java
> +    MenuDto addMenu(MenuCreationDto menuCreationDto);
하지만, API 명세서에 HTTP 201 코드를 반환합니다. 특별한 경우가 아닌 이상 201 코드인 경우, 데이터를 `body`에 담아 반환해야합니다. 때문에 `MenuDto`를 반환하도록 하였습니다.
참조: https://developer.mozilla.org/ko/docs/Web/HTTP/Status/201

2022-05-09 12:57 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/service/MenuService.java
> +    MenuDto addMenu(MenuCreationDto menuCreationDto);
그렇다면 코드 상에서는 MenuDto를 반환하도록 유지하고, API 명세서를 수정하는 방면으로 가겠습니다.

2022-05-10 09:04 UTC, iqpizza6349 commented
현재 있는 Fail은 `not covered by tests` 입니다.

2022-05-10 09:16 UTC, krapoi approved these changes

2022-05-11 04:11 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/MenuRequest.java
> +    public static class PageCannotNegative extends RuntimeException {
여기에는 message field가 없는건가요?

2022-05-11 04:14 UTC, VINTO1819 approved these changes
수고하셨습니다 merge 진행해주세요 👍️

2022-05-11 04:22 UTC, merged