🔀:: (#65) Spring Security로 JWT 인증 구현
EntryCNS/schoolmeal-back-ng pull request #66
Opened 2022-05-15 05:42 UTC by VINTO1819

close #65

2022-05-15 05:47 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/auth/service/AuthDetailsService.java
> +        return null; // TODO: 추후에 UserDetails를 상속한 AuthDetail 클래스 만들기 + 해당 메서드 구현하기
해당 `UserDetailsService`와, 여기에 사용할 `UserDetails` 클래스를 구현해야 하는데, 현재 `Auth` 도메인쪽에서 패키지 문제가 있는지라 구현하지 못했습니다.

사실 패키지 경로 옮기고 작성하면 그만이긴 하지만, 이미 그 작업을 #63에서 진행해버린지라 충돌이 일어날 거 같네요...

일단 해당 PR을 부득이하게 merge시키고, #63에서 AuthDetailsService와 UserDetails를 마무리할 계획입니다.

2022-05-15 23:14 UTC, iqpizza6349 requested changes
Code Smell 해결부탁드립니다.

2022-05-23 10:37 UTC, krapoi approved these changes

2022-05-25 00:10 UTC, iqpizza6349 requested changes
코드 리뷰 확인 및 수정바랍니다❗

2022-05-25 00:10 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/security/JwtConfiguration.java
> +@Component
`@Component`어노테이션은 필요하지 않는 어노테이션입니다.
`@ConfigurationProperties`, `@EnableConfigurationProperties`, `@ConstructorBinding`은 `@ConfigurationPropertiesScan`으로 동작하나, `@Component` 어노테이션은 `@ConfigurationPropertiesScan` 제외 대상이기때문에 서로 결합되어서는 안되는 어노테이션이므로 삭제부탁드립니다.

2022-05-25 00:16 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/security/SecurityConfiguration.java
> +                .csrf().and()
csrf는 jwt 토큰을 사용하여 인증할 것이기 때문에 비활성화하도록 했던 것 같은 데, 어떻게 생각하시나요?

2022-05-25 05:53 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/security/SecurityConfiguration.java
> +                .csrf().and()
아아 비활성화를 깜빡했네요.. 비활성화시키도록 하겠습니다!

2022-05-25 07:07 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/config/PropertiesConfiguration.java
> +public class PropertiesConfiguration {
PropertiesConfiguration 클래스 생성과 @Bean으로 지정한 이유는 무엇인가요?

2022-05-25 07:08 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/security/JwtConfiguration.java
> +@EnableConfigurationProperties
`@EnableConfigurationProperties` 어노테이션은 이미 SpringApplication에 존재하는 데, 또 지정하신 이유는 무엇인가요?

2022-05-27 14:38 UTC, ericlee05 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/global/config/PropertiesConfiguration.java
> +public class PropertiesConfiguration {
ConfigurationProperties에서 Bean 등록을 요구하는 걸로 알고 있습니다

2022-05-30 10:57 UTC, iqpizza6349 approved these changes
수고 많으셨습니다. merge 진행해주세요. 👍

2022-05-30 10:58 UTC, merged