🔀:: (#67) UserDetails 구현하도록 설정
EntryCNS/schoolmeal-back-ng pull request #68
Opened 2022-05-15 09:52 UTC by VINTO1819

2022-05-15 23:17 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
>      private UserRole role;
enum은 kotlin으로 구현한다고 하지 않았나요?
서비스와 컨트롤러는 기존 DTO들의 롬북 문제로 java로 교체되었다고는 하지만, enum까지는 그렇게 할 필요가 있을 었을 까요?

2022-05-15 23:35 UTC, iqpizza6349 requested changes
코드 리뷰 확인 및 수정 바랍니다.

2022-05-15 23:35 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
> +        return false;
false 일 경우, `계정이 만료되었음`을 의미합니다. 
고정적으로 false를 해야할 필요가 있었을 까요?

2022-05-15 23:35 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
> +        return false;
false 일 경우, `계정이 잠겨있음`을 의미합니다. 
고정적으로 false를 해야할 필요가 있었을 까요?
(개인적으로 gradle dependency 에 mail 이 추가되었기에 메일 인증을 통해 처리하는 것이 좋아보입니다.)

2022-05-15 23:35 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
> +    public boolean isCredentialsNonExpired() {
false 일 경우, `계정의 비밀번호가 만료되었음`을 의미합니다. 
고정적으로 false를 해야할 필요가 있었을 까요?

2022-05-15 23:35 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
> +    public boolean isEnabled() {
isAccountNonExpired, isAccountNonLocked, isCredentialsNonExpired 와 별개로 고정적으로 true를 반환하여
해당 계정이 계속 사용가능하도록 구현하는 것은 위험해보입니다.

2022-05-15 23:35 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
> +public class User implements UserDetails {
UserDetails 인터페이스는 내부적으로 Serializable 을 상속하고 있습니다.
SonarCloud의 CodeSmell에서도 적발하였듯이, CommonUser와 OAuthUser는 각각 Serializable 을 상속하고 있지 않아
오류가 발생할 가능성이 매우 높습니다. 
만일 각 연관관계 엔티티들을 직렬화하고 싶지 않다면, transient 키워드를 사용하여 직렬화에서 제외시킬 수 있습니다.

2022-05-18 01:41 UTC, ericlee05 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
> +public class User implements UserDetails {
`transient` 키워드를 통해서 CommonUser랑 OAuthUser는 직렬화 대상에서 제외시키도록 하겠습니다

2022-05-18 01:43 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
>      private UserRole role;
음 Kotlin으로 작성되어 있었군요.. 몇주 전 issue에서 생성된지라 눈치채지 못했습니다 ㅜㅜ
핫픽스에서 고칠까요 아니면 여기서 고칠까요?

2022-05-18 01:45 UTC, VINTO1819 commented
`UserDetails`를 구현함으로서 만들어진 오버라이딩 메서드에 대해서는 잠시 논의해 볼 필요가 있을 거 같습니다.
해당 인터페이스에서 구현을 요구하는 메서드들 중 일부는 현재 Entity로는 구현하기 힘들어 보이네요.

2022-05-18 23:02 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
>      private UserRole role;
서비스 추상화, 서비스 구현, 단위 테스트, 컨트롤러 순으로 개발을 진행할 것 같습니다.
하지만, 각 도메인 구현 이슈에는 서비스 구현과 컨트롤러가 있기 때문에 먼저 핫픽스 진행 후,
서비스 구현하시면 될 것 같습니다.

2022-05-21 04:40 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/user/entity/User.java
>      private UserRole role;
그렇다면 해당 PR에서는 넘어간 뒤, 새 핫픽스를 진행하고 나서 서비스 개발을 진행하도록 하겠습니다.

2022-05-23 10:38 UTC, iqpizza6349 approved these changes
확인하였습니다. merge 진행해주세요. 👍

2022-05-23 10:39 UTC, krapoi approved these changes

2022-05-23 10:39 UTC, merged