🔀:: (#81) 리뷰 서비스 및 컨트롤러 작성, 테스트 ❌
EntryCNS/schoolmeal-back-ng pull request #82
Opened 2022-06-15 07:02 UTC by krapoi

create #81

2022-06-15 23:33 UTC, VINTO1819 approved these changes

2022-06-15 23:34 UTC, VINTO1819 commented
Conflict만 해결해 주시면 될 거 같습니다!

2022-06-16 00:39 UTC, iqpizza6349 requested changes
코드 리뷰 확인 및 수정바랍니다. ☄

2022-06-16 00:39 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/presentation/ReviewController.java
> +    @GetMapping
API 명세서에는 `GetMapping`이 아닌 `PostMapping`으로 작성되어 있습니다.
또, 작성하는 기능이므로 `PostMapping`으로 바꿀 필요가 있다고 생각이 듭니다.

2022-06-16 00:39 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/presentation/ReviewController.java
> +    public WriteReviewResponseDto writeReview(User user, WriteReviewRequestDto writeReviewRequestDto) {
`/reviews` 매핑으로 임명되는 컨트롤러에는 바인딩으로 `User` 인자값이 들어가지 않습니다.
보통 `Authentication` 혹은 `Principal`, `UserDetails` 가 바인딩으로 들어갑니다.
현재 바인딩을 `Authentication`과 `Principal`만을 가져와 사용하고 있습니다.
하지만 `Principal` 인터페이스만을 사용해본 결과, 잘못된 데이터를 바인딩해주는 경우가 있기 때문에
`Authentication` 인터페이스를 인자값으로 설정해주세요.
또, `WriteReviewRequestDto`는 API 명세서상에 RequestBody로 값을 보내므로, 
`@RequestBody` 어노테이션을 사용해주세요.

2022-06-16 00:39 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/presentation/ReviewController.java
> +    public ReviewListDto getReviewList(LocalDate date, ReviewTime reviewTime, int page){
API 명세서상에는 `page` Parameter가 존재하지 않으나, 필요해보이므로 **백엔드 PM**과 상의 후 진행하면 될 것 같습니다.
`date`와 `reviewTime`은 `@RequestParameter`를 추가하여 QueryString으로 추가한다는 것을 명시해줘야합니다.
또, `date`의 타입은 `LocalDate`이므로 데이터 포맷 문제가 발생하게 되므로 `@DateTimeFormat` 혹은 `Component`를 새로 생성하여 `String`을 받아들이면 파싱할 수 있도록 구현해야합니다. 
`reviewTime`은 `@RequestParameter`만 추가하면 될 것 같습니다.

2022-06-16 00:39 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/presentation/dto/request/WriteReviewRequestDto.java
> +    private LocalDate date;
`@DateTimeFormat` 어노테이션을 추가해야 데이터 컨버터 문제가 발생하지 않습니다.

2022-06-16 00:39 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/presentation/dto/request/WriteReviewRequestDto.java
>      private ReviewTime reviewTime;
reviewTime은 Enum입니다. Enum을 그냥 매핑할 경우 데이터 포맷하는 과정에서 문제가 발생합니다.
Enum class에서 `@JsonCreator `을 붙인 static 메소드를 사용하여 Enum을 변환하도록 하면 됩니다.
```java
@JsonCreater
public EnumName from(String s) {
    return EnumName.valueOf(s.toUpperCase());
}
```

2022-06-16 00:39 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/repository/ReviewRepository.java
> +    Page<Review> findAllByDateAndReviewTime(LocalDate date, @NotNull ReviewTime reviewTime, Pageable pageable);
JPQL(=Query)를 혹시 볼 수 있을 까요?
- Comment로 남겨주세요.

2022-06-16 00:39 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/service/ReviewServiceImpl.java
> +public class ReviewServiceImpl implements ReviewService {
`@Service` 어노테이션이 없으면 `Component`에 올라가지 않습니다.
`@Service` 어노테이션을 추가해주세요.

2022-07-13 09:13 UTC, ericlee05 approved these changes

2022-07-14 08:45 UTC, iqpizza6349 requested changes
코드 리뷰 확인 및 수정 바랍니다. 📝

2022-07-14 08:45 UTC, iqpizza6349 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/review/service/ReviewServiceImpl.java
> +public class ReviewServiceImpl implements ReviewService {
@Transactional 어노테이션 추가가 필요합니다.

2022-07-14 08:55 UTC, iqpizza6349 approved these changes
🚀 merge 진행해주세요.

2022-07-14 08:55 UTC, merged