🔀:: (#8) 메뉴 요청 엔티티
EntryCNS/schoolmeal-back-ng pull request #9
Opened 2022-03-20 10:41 UTC by VINTO1819

close #8

2022-03-20 11:08 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/MenuRequest.java
> +    private Boolean anonymous;
저희 디자인에는 메뉴신청이 전부다 익명으로 되어있던데 이거 필요하지 않을수도 있을 거 같아요
어떻게 생각하시나요?

빼도 괜찮다면 ErdCloud랑 코드에서 anonymous 칼럼은 제외하도록 하겠습니다

2022-03-21 10:57 UTC, krapoi requested changes

2022-03-21 10:57 UTC, krapoi commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/MenuRequest.java
> +    private Boolean anonymous;
원래 익명으로 작성하던거라서 아마 메뉴신청이 다 익명인 것으로 추정되는데, 제 생각에도 제외해도 될 것 같습니다.

2022-03-21 11:00 UTC, VINTO1819 commented on src/main/java/kr/hs/dgsw/cns/schoolmealbacksetup/domain/menu/entity/MenuRequest.java
> +    private Boolean anonymous;
수정했습니다 :+1:

2022-03-21 11:00 UTC, krapoi approved these changes
확인헀습니다.

2022-03-21 11:01 UTC, merged